# Generated by Django 4.2 on 2024-10-11 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('A', 'Category A'), ('B', 'Category B'), ('C', 'Category C')], default='A', max_length=1),
        ),
    ]
