# Generated by Django 4.2 on 2024-10-04 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='community',
            name='image',
        ),
        migrations.CreateModel(
            name='CommunityImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('community_image', models.ImageField(upload_to='community_images/')),
                ('community', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='community_images', to='communities.community')),
            ],
        ),
    ]
