# Generated by Django 4.2 on 2024-09-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Community',
        ),
    ]
