# Generated by Django 4.2 on 2024-09-30 12:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('communities', '0002_community_unusable_alter_community_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='unusable',
            field=models.ManyToManyField(related_name='community_unusable', to=settings.AUTH_USER_MODEL),
        ),
    ]
