# Generated by Django 4.2 on 2024-10-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0002_community_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='category',
            field=models.CharField(choices=[('A', '정보'), ('B', '잡담'), ('C', '홍보')], default='A', max_length=1),
        ),
    ]
