# Generated by Django 4.2 on 2024-10-01 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0003_alter_community_unusable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
