# Generated by Django 4.2 on 2024-10-01 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('communities', '0004_alter_community_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='unusable',
            new_name='unusables',
        ),
    ]
