# Generated by Django 4.2 on 2024-10-06 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='new_password',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
