# Generated by Django 4.2 on 2024-10-16 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('AUTHOR', 'AUTHOR'), ('NORMAL', 'NORMAL')], default='NORMAL', max_length=6),
        ),
    ]
