# Generated by Django 4.2 on 2024-10-16 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='author_verification_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
