# Generated by Django 4.2 on 2024-10-07 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_new_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('author', 'author'), ('nomal', 'nomal')], default='nomal', max_length=6),
        ),
    ]
