# Generated by Django 4.2 on 2024-10-07 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('author', 'author'), ('normal', 'normal')], default='normal', max_length=6),
        ),
    ]
