# Generated by Django 4.2 on 2024-09-26 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_user_id_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribings',
            field=models.ManyToManyField(related_name='subscribes', to=settings.AUTH_USER_MODEL),
        ),
    ]
