# Generated by Django 4.2 on 2024-09-26 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='author',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='image',
        ),
    ]
