# Generated by Django 4.2 on 2024-09-30 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='user',
        ),
        migrations.AlterField(
            model_name='journal',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
