# Generated by Django 4.2 on 2024-10-01 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_remove_journal_user_alter_journal_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_comment_likes', to='journals.comment'),
        ),
    ]
