# Generated by Django 4.2 on 2024-10-01 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_alter_journal_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='image',
        ),
        migrations.CreateModel(
            name='JournalImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='journal_images/')),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_images', to='journals.journal')),
            ],
        ),
    ]
