# Generated by Django 4.2 on 2024-10-01 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_remove_journal_image_journalimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal_images/'),
        ),
    ]
