# Generated by Django 4.2 on 2024-09-30 04:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0005_comment_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='likes',
            field=models.ManyToManyField(related_name='journal_like', to=settings.AUTH_USER_MODEL),
        ),
    ]
