# Generated by Django 4.2 on 2024-10-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_journalimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='JournalImage',
        ),
    ]
