# Generated by Django 4.2 on 2024-10-02 05:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journals', '0007_journal_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
