# Generated by Django 4.2 on 2024-09-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='business_hour',
            new_name='opening_hours',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='place_info',
            new_name='place_description',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='place',
            new_name='place_name',
        ),
    ]
