# Generated by Django 4.2 on 2024-09-30 10:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_rename_business_hour_location_opening_hours_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='locationsave',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='locationsave',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='locations.location'),
        ),
        migrations.AddField(
            model_name='locationsave',
            name='saved_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='locationsave',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='locationsave',
            unique_together={('user', 'location')},
        ),
        migrations.RemoveField(
            model_name='locationsave',
            name='locationsave',
        ),
        migrations.RemoveField(
            model_name='locationsave',
            name='save_type',
        ),
    ]
